DROP DATABASE IF EXISTS Assignment1;
CREATE DATABASE IF NOT EXISTS Assignment1;
USE Assignment1;

CREATE TABLE TraineeID(
	TraineeID	SMALLINT UNSIGNED 	 PRIMARY KEY,
    Full_Name	VARCHAR(50) NOT NULL,
    Birth_Date DATE NOT NULL,
    Gender ENUM('male','female','unknown'),
    ET_IQ	TINYINT	UNSIGNED	CHECK(0<ET_IQ < 20) ,
    ET_Gmath	TINYINT UNSIGNED	CHECK(0<(ET_Gmath)<20),
	ET_English	TINYINT UNSIGNED	CHECK(0<(ET_English)<50),
    Training_Class	TINYINT UNSIGNED,
    Evaluation_Notes	TINYINT UNSIGNED,
    VTI_Account	TINYINT  NOT NULL UNIQUE AUTO_INCREMENT
);

-- EXERCISE 2
CREATE TABLE BAI2(
	ID	TINYINT UNSIGNED	 PRIMARY KEY	AUTO_INCREMENT,
    NAME1	VARCHAR(50) NOT NULL,
    CODE1	VARCHAR(5)		CHECK(LENGTH(CODE1) <	6)	UNIQUE,
    ModifiedDate	DATETIME
);


-- EXERCISE 3
CREATE TABLE	BAI3(
	ID	TINYINT UNSIGNED	PRIMARY	KEY	AUTO_INCREMENT,
    NAME1	VARCHAR(50)	NOT NULL,
    BirthDate	DATE,
    Gender	ENUM('mane',	'female',	'Unknown'),
    IsDeletedFlag	ENUM('ĐANG HOẠT ĐỘNG','ĐÃ XÓA')
);


	